# Generated by Django 4.2.6 on 2023-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='adicionar_pedido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
