# Generated by Django 4.2.6 on 2023-10-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FormaPagamento', models.CharField(choices=[('boleto', 'boleto'), ('cartao', 'cartao'), ('pix', 'pix')], max_length=10)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.carrinho')),
            ],
        ),
    ]
