# Generated by Django 4.2.6 on 2023-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
